/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.baxtheman.stacktracejs.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import it.baxtheman.stacktracejs.model.jserrorlog;
import it.baxtheman.stacktracejs.service.jserrorlogLocalService;
import it.baxtheman.stacktracejs.service.persistence.jserrorlogPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the jserrorlog local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.baxtheman.stacktracejs.service.impl.jserrorlogLocalServiceImpl}.
 * </p>
 *
 * @author @baxtheman
 * @see it.baxtheman.stacktracejs.service.impl.jserrorlogLocalServiceImpl
 * @see it.baxtheman.stacktracejs.service.jserrorlogLocalServiceUtil
 * @generated
 */
public abstract class jserrorlogLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements jserrorlogLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link it.baxtheman.stacktracejs.service.jserrorlogLocalServiceUtil} to access the jserrorlog local service.
	 */

	/**
	 * Adds the jserrorlog to the database. Also notifies the appropriate model listeners.
	 *
	 * @param jserrorlog the jserrorlog
	 * @return the jserrorlog that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public jserrorlog addjserrorlog(jserrorlog jserrorlog)
		throws SystemException {
		jserrorlog.setNew(true);

		return jserrorlogPersistence.update(jserrorlog);
	}

	/**
	 * Creates a new jserrorlog with the primary key. Does not add the jserrorlog to the database.
	 *
	 * @param jserrorlogId the primary key for the new jserrorlog
	 * @return the new jserrorlog
	 */
	@Override
	public jserrorlog createjserrorlog(long jserrorlogId) {
		return jserrorlogPersistence.create(jserrorlogId);
	}

	/**
	 * Deletes the jserrorlog with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jserrorlogId the primary key of the jserrorlog
	 * @return the jserrorlog that was removed
	 * @throws PortalException if a jserrorlog with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public jserrorlog deletejserrorlog(long jserrorlogId)
		throws PortalException, SystemException {
		return jserrorlogPersistence.remove(jserrorlogId);
	}

	/**
	 * Deletes the jserrorlog from the database. Also notifies the appropriate model listeners.
	 *
	 * @param jserrorlog the jserrorlog
	 * @return the jserrorlog that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public jserrorlog deletejserrorlog(jserrorlog jserrorlog)
		throws SystemException {
		return jserrorlogPersistence.remove(jserrorlog);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(jserrorlog.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return jserrorlogPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link it.baxtheman.stacktracejs.model.impl.jserrorlogModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return jserrorlogPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link it.baxtheman.stacktracejs.model.impl.jserrorlogModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return jserrorlogPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return jserrorlogPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return jserrorlogPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public jserrorlog fetchjserrorlog(long jserrorlogId)
		throws SystemException {
		return jserrorlogPersistence.fetchByPrimaryKey(jserrorlogId);
	}

	/**
	 * Returns the jserrorlog with the primary key.
	 *
	 * @param jserrorlogId the primary key of the jserrorlog
	 * @return the jserrorlog
	 * @throws PortalException if a jserrorlog with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public jserrorlog getjserrorlog(long jserrorlogId)
		throws PortalException, SystemException {
		return jserrorlogPersistence.findByPrimaryKey(jserrorlogId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return jserrorlogPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the jserrorlogs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link it.baxtheman.stacktracejs.model.impl.jserrorlogModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of jserrorlogs
	 * @param end the upper bound of the range of jserrorlogs (not inclusive)
	 * @return the range of jserrorlogs
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<jserrorlog> getjserrorlogs(int start, int end)
		throws SystemException {
		return jserrorlogPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of jserrorlogs.
	 *
	 * @return the number of jserrorlogs
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getjserrorlogsCount() throws SystemException {
		return jserrorlogPersistence.countAll();
	}

	/**
	 * Updates the jserrorlog in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param jserrorlog the jserrorlog
	 * @return the jserrorlog that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public jserrorlog updatejserrorlog(jserrorlog jserrorlog)
		throws SystemException {
		return jserrorlogPersistence.update(jserrorlog);
	}

	/**
	 * Returns the jserrorlog local service.
	 *
	 * @return the jserrorlog local service
	 */
	public it.baxtheman.stacktracejs.service.jserrorlogLocalService getjserrorlogLocalService() {
		return jserrorlogLocalService;
	}

	/**
	 * Sets the jserrorlog local service.
	 *
	 * @param jserrorlogLocalService the jserrorlog local service
	 */
	public void setjserrorlogLocalService(
		it.baxtheman.stacktracejs.service.jserrorlogLocalService jserrorlogLocalService) {
		this.jserrorlogLocalService = jserrorlogLocalService;
	}

	/**
	 * Returns the jserrorlog remote service.
	 *
	 * @return the jserrorlog remote service
	 */
	public it.baxtheman.stacktracejs.service.jserrorlogService getjserrorlogService() {
		return jserrorlogService;
	}

	/**
	 * Sets the jserrorlog remote service.
	 *
	 * @param jserrorlogService the jserrorlog remote service
	 */
	public void setjserrorlogService(
		it.baxtheman.stacktracejs.service.jserrorlogService jserrorlogService) {
		this.jserrorlogService = jserrorlogService;
	}

	/**
	 * Returns the jserrorlog persistence.
	 *
	 * @return the jserrorlog persistence
	 */
	public jserrorlogPersistence getjserrorlogPersistence() {
		return jserrorlogPersistence;
	}

	/**
	 * Sets the jserrorlog persistence.
	 *
	 * @param jserrorlogPersistence the jserrorlog persistence
	 */
	public void setjserrorlogPersistence(
		jserrorlogPersistence jserrorlogPersistence) {
		this.jserrorlogPersistence = jserrorlogPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("it.baxtheman.stacktracejs.model.jserrorlog",
			jserrorlogLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"it.baxtheman.stacktracejs.model.jserrorlog");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return jserrorlog.class;
	}

	protected String getModelClassName() {
		return jserrorlog.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = jserrorlogPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = it.baxtheman.stacktracejs.service.jserrorlogLocalService.class)
	protected it.baxtheman.stacktracejs.service.jserrorlogLocalService jserrorlogLocalService;
	@BeanReference(type = it.baxtheman.stacktracejs.service.jserrorlogService.class)
	protected it.baxtheman.stacktracejs.service.jserrorlogService jserrorlogService;
	@BeanReference(type = jserrorlogPersistence.class)
	protected jserrorlogPersistence jserrorlogPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private jserrorlogLocalServiceClpInvoker _clpInvoker = new jserrorlogLocalServiceClpInvoker();
}