/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.baxtheman.stacktracejs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the jserrorlog service. Represents a row in the &quot;stacktracejs_jserrorlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link it.baxtheman.stacktracejs.model.impl.jserrorlogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link it.baxtheman.stacktracejs.model.impl.jserrorlogImpl}.
 * </p>
 *
 * @author @baxtheman
 * @see jserrorlog
 * @see it.baxtheman.stacktracejs.model.impl.jserrorlogImpl
 * @see it.baxtheman.stacktracejs.model.impl.jserrorlogModelImpl
 * @generated
 */
public interface jserrorlogModel extends BaseModel<jserrorlog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jserrorlog model instance should use the {@link jserrorlog} interface instead.
	 */

	/**
	 * Returns the primary key of this jserrorlog.
	 *
	 * @return the primary key of this jserrorlog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jserrorlog.
	 *
	 * @param primaryKey the primary key of this jserrorlog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jserrorlog ID of this jserrorlog.
	 *
	 * @return the jserrorlog ID of this jserrorlog
	 */
	public long getJserrorlogId();

	/**
	 * Sets the jserrorlog ID of this jserrorlog.
	 *
	 * @param jserrorlogId the jserrorlog ID of this jserrorlog
	 */
	public void setJserrorlogId(long jserrorlogId);

	/**
	 * Returns the group ID of this jserrorlog.
	 *
	 * @return the group ID of this jserrorlog
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this jserrorlog.
	 *
	 * @param groupId the group ID of this jserrorlog
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this jserrorlog.
	 *
	 * @return the company ID of this jserrorlog
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this jserrorlog.
	 *
	 * @param companyId the company ID of this jserrorlog
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this jserrorlog.
	 *
	 * @return the user ID of this jserrorlog
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this jserrorlog.
	 *
	 * @param userId the user ID of this jserrorlog
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this jserrorlog.
	 *
	 * @return the user uuid of this jserrorlog
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this jserrorlog.
	 *
	 * @param userUuid the user uuid of this jserrorlog
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this jserrorlog.
	 *
	 * @return the user name of this jserrorlog
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this jserrorlog.
	 *
	 * @param userName the user name of this jserrorlog
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this jserrorlog.
	 *
	 * @return the create date of this jserrorlog
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this jserrorlog.
	 *
	 * @param createDate the create date of this jserrorlog
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the location of this jserrorlog.
	 *
	 * @return the location of this jserrorlog
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this jserrorlog.
	 *
	 * @param location the location of this jserrorlog
	 */
	public void setLocation(String location);

	/**
	 * Returns the msg of this jserrorlog.
	 *
	 * @return the msg of this jserrorlog
	 */
	@AutoEscape
	public String getMsg();

	/**
	 * Sets the msg of this jserrorlog.
	 *
	 * @param msg the msg of this jserrorlog
	 */
	public void setMsg(String msg);

	/**
	 * Returns the url of this jserrorlog.
	 *
	 * @return the url of this jserrorlog
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this jserrorlog.
	 *
	 * @param url the url of this jserrorlog
	 */
	public void setUrl(String url);

	/**
	 * Returns the line of this jserrorlog.
	 *
	 * @return the line of this jserrorlog
	 */
	@AutoEscape
	public String getLine();

	/**
	 * Sets the line of this jserrorlog.
	 *
	 * @param line the line of this jserrorlog
	 */
	public void setLine(String line);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.baxtheman.stacktracejs.model.jserrorlog jserrorlog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.baxtheman.stacktracejs.model.jserrorlog> toCacheModel();

	@Override
	public it.baxtheman.stacktracejs.model.jserrorlog toEscapedModel();

	@Override
	public it.baxtheman.stacktracejs.model.jserrorlog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}