/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.baxtheman.stacktracejs.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import it.baxtheman.stacktracejs.model.jserrorlog;
import it.baxtheman.stacktracejs.service.jserrorlogLocalServiceUtil;

/**
 * The extended model base implementation for the jserrorlog service. Represents a row in the &quot;stacktracejs_jserrorlog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link jserrorlogImpl}.
 * </p>
 *
 * @author @baxtheman
 * @see jserrorlogImpl
 * @see it.baxtheman.stacktracejs.model.jserrorlog
 * @generated
 */
public abstract class jserrorlogBaseImpl extends jserrorlogModelImpl
	implements jserrorlog {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jserrorlog model instance should use the {@link jserrorlog} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			jserrorlogLocalServiceUtil.addjserrorlog(this);
		}
		else {
			jserrorlogLocalServiceUtil.updatejserrorlog(this);
		}
	}
}